### ISSUE TITLE
Pastebin account

### ISSUE THREAD

**Issue by seeya** [edoz90/pastego#1]
How do you login with a pastebin account? I can't seem to find anything related in the source.

**Comment by edoz90** [comment]
Hi!

There's no login, if you managed to have a PRO account you have to whitelist your IP: https://pastebin.com/scraping

![screenshot from 2017-09-03 09-00-48](https://user-images.githubusercontent.com/6991986/30001180-7a609260-9086-11e7-93f1-6826132909e3.png)

**Comment by seeya** [comment]
Thanks, maybe you can add this to the documentation along side with the direct link "https://pastebin.com/api_scraping_faq".
